
ROOT_PATH = ..

SRCS = \
	$(ROOT_PATH)/main.cpp \
	$(ROOT_PATH)/sidekickio.cpp

INCLUDES = \
	$(ROOT_PATH)

CFLAGS := -lusb-1.0

LDFLAGS := -Wl,-lusb-1.0

PROJECT := SidekickIO

include ../../common-standalone.mk
