
ROOT_PATH = ..

SRCS = \
	$(ROOT_PATH)/i2cdevlib/Arduino/MPU6050/MPU6050.cpp \
	$(ROOT_PATH)/i2cdevlib/Arduino/I2Cdev/I2Cdev.cpp \
	$(ROOT_PATH)/Arduino.cpp


INCLUDES = \
	$(ROOT_PATH)/i2cdevlib/Arduino/MPU6050 \
	$(ROOT_PATH)/i2cdevlib/Arduino/I2Cdev \
	$(ROOT_PATH)

PROJECT := IMUExample

DEFINES := ARDUINO=100

include ../../../common-standalone.mk
